name: RPGfy
version: 1.0-SNAPSHOT
author: Juampa99
main: git.juampa99.rpgfy.Rpgfy
api-version: 1.16

commands:
  spawngear:
    description: Gives a custom weapon or armor to the caller
    usage: >
          /spawngear armor <type> <name> <armor?> <armor_toughness?> <effect1?> <value1?> ... <effectN?> <valueN?>
          /spawngear weapon <type> <name> <damage?> <attack_speed?> <effect1?> <value1?> ... <effectN?> <valueN?>
          (Parameters marked with "?" are optional)
    permission: rpgfy.spawngear
  list:
    description: Shows a list of custom items or effects
    usage: /list <effects/items>
    permission: rpgfy.list